// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/GiantTypographicPortfolio-89K1CJ/VegaFolio.tsx": () => import("../components/mockups/templates/GiantTypographicPortfolio-89K1CJ/VegaFolio.tsx")
};
